#ifndef __AICULT_H
#define __AICULT_H

#include "ai.h"


extern AISTATE cultistBurnChase;
extern AISTATE cultistBurnGoto;
extern AISTATE cultistBurnSearch;

extern AISTATE playerBurnChase;
extern AISTATE playerBurnGoto;
extern AISTATE playerBurnSearch;

extern AISTATE zombieABurnChase;
extern AISTATE zombieABurnGoto;
extern AISTATE zombieABurnSearch;

extern AISTATE zombieFBurnChase;
extern AISTATE zombieFBurnGoto;
extern AISTATE zombieFBurnSearch;


#endif	// __AICULT_H
